server:
  port: 8080

spring:
  application:
    name: lagou-service-resume
  datasource:
    url: jdbc:mysql://120.27.12.173:3306/logistics?useUnicode=true&characterEncoding=utf8
    username: lxq
    password: Lxq410221@5214
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@

